### ISSUE TITLE
The initializer of an upgrade should not be run in an already initialized contract

### ISSUE THREAD

**Issue by facuspagnuolo** [zeppelinos/zos-lib#158]
The `isInitializer` modifier has a `migrationId` argument. Although its usage/meaning is not well documented, we think it was implied that this could be the version string, such as OpenZeppelin's `"1.9.0"`. However, if at version `"1.10.0"` the contracts are changed to use this new version as the `migrationId`, this would enable running the initializer in an already initialized contract.

Example:
```
contract MyToken is Migratable {
   function initialize() isInitializer("Token", "1.9.0") {
       mint(owner, 100);
   }
   ...
}
```

Changing `"1.9.0"` to `"1.10.0"` in a newer version would enable running the `initialize` function again, and thus minting more balance than should be.

cc @frangio

**Comment by roschler** [comment]
So the contract's state variables are not  preserved across upgrades (new deployments)?

**Comment by frangio** [comment]
@facuspagnuolo I changed the description to try to explain the problem a bit better.

**Comment by spalladino** [comment]
@frangio can't the issue be solved if we add an extra `mapping (string => bool) initialized`, that keeps track of whether the contract was initialized, for any version? The code for `isInitializable` should then be:

```solidity
modifier isInitializer(string contractName, string migrationId) {
    require(!isMigrated(contractName, migrationId));
    require(!isInitialized(contractName));
    _;
    emit Migrated(contractName, migrationId);
    initialized[contractName] = true;
    migrated[contractName][migrationId] = true;
  }
```

**Comment by roschler** [comment]
Hello Open Zeppelin team. Pardon the thread "drive-by" but I'm watching this repo and this thread caught my keen attention.  Below is the code I currently have for my first dApp with ZeppelinOS.  How will my code be affected by this issue, given that I'm chaining from my `initializer()` call to the `MintableERC721.initializer()` call, since I inherit from that contract?:

I have a contract named `GameFactory` that inherits from `MintableERC721`.  `MintableERC721` has its own `initialize()` method marked with the `IsInitializer` decorator.  My contract has its own `initialize()` method.  I have marked as shown below.  As you can see I'm calling the `MintableERC721` contract's `initialize()` method from my `initialize()` method.  Will everything work properly as far as the initializer methods being called?:

```sol
    // This method initializes this contract and as a side effect, makes the caller
    //  (msg.sender) the owner of this contract.
    //
    // NOTE: Whoever calls this method becomes the Adminstrator of the contract!
    function initialize() public payable isInitializer("GameFactory", "1.0.0")  {
        // Assign the caller of this method as the Adminstrator of this contract.
        require(address(msg.sender) != 0, "The message sender address is not set.");
        this.s_adminAddr = msg.sender;
                
        // We inherit from MintableERC721Token, so we call its initialize() method with 
        //  the House address as the "sender" parameter.  MintableERC721Token's will
        //  in turn call Ownable's initialize() method with that value 
        //  thereby making the the sender the owner of this contract.
        //
        // Token Name   : EtherBandBattlesToken
        // Token Symbol : EBB
        MintableERC721Token.intialize(msg.sender, "EtherBandBattlesToken", "EBB");
    }
}
```
