### ISSUE TITLE
Add upgradeToAndMigrate helper function to BaseAppManager

### ISSUE THREAD

**Issue by maraoz** [zeppelinos/zos-lib#49]
We currently have two options for upgrading a proxied contract:
- `upgradeTo`, which changes the implementation and does nothing else.
- `upgradeToAndCall`, which changes the implementation and allows the execution of arbitrary code in the resulting contract.

The former is easy to use but of limited use, and the latter is very powerful but hard to use. 
I propose creating an intermediate version, `upgradeToAndMigrate`, that changes the implementation and then calls a `migrate()` function with no parameters. This would allow an easy way of implementing simple migrations (where no parameters are needed) without having to craft the call data (which is too complex to some developers)

**Comment by facuspagnuolo** [comment]
We decided not to overload the proxy with extra functionality in order to leave it as minimal as possible. However, a similar "default" behavior is already implemented at a CLI level when upgrading, it will call the `initialize` method unless another was specified, which is abstracting the complexity of dealing with the `data` parameter to perform the desired call.
